name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the env value where this workflow runs
        default: dev
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
  codes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  build:
    runs-on: ubuntu-latest
    needs: codes
    steps:
      - name: Build container
        run: echo "Docker container build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test code
        run: echo "Test code"

  deploy:
    if: inputs.environment == 'dev'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
